[window]
opacity = 0.96
blur = true
title = ""
dynamic_title = false
decorations_theme_variant = "Dark"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[selection]
save_to_clipboard = true

[terminal]
osc52 =  "CopyPaste"
